[2022-08-04 07:51:48,403] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.format_to_parquet_task scheduled__2022-08-03T00:00:00+00:00 [queued]>
[2022-08-04 07:51:48,412] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.format_to_parquet_task scheduled__2022-08-03T00:00:00+00:00 [queued]>
[2022-08-04 07:51:48,412] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-08-04 07:51:48,412] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-08-04 07:51:48,412] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-08-04 07:51:48,422] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): format_to_parquet_task> on 2022-08-03 00:00:00+00:00
[2022-08-04 07:51:48,430] {standard_task_runner.py:52} INFO - Started process 125 to run task
[2022-08-04 07:51:48,432] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'format_to_parquet_task', 'scheduled__2022-08-03T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag1.py', '--cfg-path', '/tmp/tmpfs9qu78y', '--error-file', '/tmp/tmp8iqw7p8h']
[2022-08-04 07:51:48,433] {standard_task_runner.py:77} INFO - Job 4: Subtask format_to_parquet_task
[2022-08-04 07:51:48,477] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.format_to_parquet_task scheduled__2022-08-03T00:00:00+00:00 [running]> on host 5a421212560b
[2022-08-04 07:51:48,521] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=format_to_parquet_task
AIRFLOW_CTX_EXECUTION_DATE=2022-08-03T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-03T00:00:00+00:00
[2022-08-04 07:51:48,631] {python.py:175} INFO - Done. Returned value was: None
[2022-08-04 07:51:48,642] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=format_to_parquet_task, execution_date=20220803T000000, start_date=20220804T075148, end_date=20220804T075148
[2022-08-04 07:51:48,684] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-08-04 07:51:48,717] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-08-04 08:01:56,622] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.format_to_parquet_task scheduled__2022-08-03T00:00:00+00:00 [queued]>
[2022-08-04 08:01:56,642] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.format_to_parquet_task scheduled__2022-08-03T00:00:00+00:00 [queued]>
[2022-08-04 08:01:56,642] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-08-04 08:01:56,643] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-08-04 08:01:56,643] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-08-04 08:01:56,655] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): format_to_parquet_task> on 2022-08-03 00:00:00+00:00
[2022-08-04 08:01:56,663] {standard_task_runner.py:52} INFO - Started process 115 to run task
[2022-08-04 08:01:56,666] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'format_to_parquet_task', 'scheduled__2022-08-03T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp_696k8pz', '--error-file', '/tmp/tmpmywrdlk_']
[2022-08-04 08:01:56,667] {standard_task_runner.py:77} INFO - Job 6: Subtask format_to_parquet_task
[2022-08-04 08:01:56,722] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.format_to_parquet_task scheduled__2022-08-03T00:00:00+00:00 [running]> on host 86bd73de96a7
[2022-08-04 08:01:56,781] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=format_to_parquet_task
AIRFLOW_CTX_EXECUTION_DATE=2022-08-03T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-03T00:00:00+00:00
[2022-08-04 08:01:56,823] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 33, in format_to_parquet
    table = pq.read_table(src_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/parquet.py", line 1869, in read_table
    coerce_int96_timestamp_unit=coerce_int96_timestamp_unit
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/parquet.py", line 1679, in __init__
    [fragment], schema=fragment.physical_schema,
  File "pyarrow/_dataset.pyx", line 952, in pyarrow._dataset.Fragment.physical_schema.__get__
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Could not open Parquet input source '/opt/***/yellow_tripdata_2021-01.paquet': Parquet magic bytes not found in footer. Either the file is corrupted or this is not a parquet file.
[2022-08-04 08:01:56,840] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=format_to_parquet_task, execution_date=20220803T000000, start_date=20220804T080156, end_date=20220804T080156
[2022-08-04 08:01:56,855] {standard_task_runner.py:92} ERROR - Failed to execute job 6 for task format_to_parquet_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 33, in format_to_parquet
    table = pq.read_table(src_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/parquet.py", line 1869, in read_table
    coerce_int96_timestamp_unit=coerce_int96_timestamp_unit
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/parquet.py", line 1679, in __init__
    [fragment], schema=fragment.physical_schema,
  File "pyarrow/_dataset.pyx", line 952, in pyarrow._dataset.Fragment.physical_schema.__get__
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Could not open Parquet input source '/opt/***/yellow_tripdata_2021-01.paquet': Parquet magic bytes not found in footer. Either the file is corrupted or this is not a parquet file.
[2022-08-04 08:01:56,879] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-08-04 08:01:56,920] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
