[2022-07-31 18:17:58,761] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.format_to_parquet_task manual__2022-07-31T18:12:53.867792+00:00 [queued]>
[2022-07-31 18:17:58,769] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.format_to_parquet_task manual__2022-07-31T18:12:53.867792+00:00 [queued]>
[2022-07-31 18:17:58,769] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-07-31 18:17:58,769] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2022-07-31 18:17:58,769] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-07-31 18:17:58,778] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): format_to_parquet_task> on 2022-07-31 18:12:53.867792+00:00
[2022-07-31 18:17:58,785] {standard_task_runner.py:52} INFO - Started process 421 to run task
[2022-07-31 18:17:58,787] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'format_to_parquet_task', 'manual__2022-07-31T18:12:53.867792+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp217v2g22', '--error-file', '/tmp/tmpp80iozld']
[2022-07-31 18:17:58,788] {standard_task_runner.py:77} INFO - Job 36: Subtask format_to_parquet_task
[2022-07-31 18:17:58,837] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.format_to_parquet_task manual__2022-07-31T18:12:53.867792+00:00 [running]> on host 730e9829e9ac
[2022-07-31 18:17:58,876] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=format_to_parquet_task
AIRFLOW_CTX_EXECUTION_DATE=2022-07-31T18:12:53.867792+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-31T18:12:53.867792+00:00
[2022-07-31 18:17:58,877] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 32, in format_to_parquet
    table = pq.write_table(src_file, 'yellow_data.parquet')
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/parquet.py", line 1971, in write_table
    where, table.schema,
AttributeError: 'str' object has no attribute 'schema'
[2022-07-31 18:17:58,885] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=data_ingestion_gcs_dag, task_id=format_to_parquet_task, execution_date=20220731T181253, start_date=20220731T181758, end_date=20220731T181758
[2022-07-31 18:17:58,896] {standard_task_runner.py:92} ERROR - Failed to execute job 36 for task format_to_parquet_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 32, in format_to_parquet
    table = pq.write_table(src_file, 'yellow_data.parquet')
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/parquet.py", line 1971, in write_table
    where, table.schema,
AttributeError: 'str' object has no attribute 'schema'
[2022-07-31 18:17:58,919] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-07-31 18:17:58,956] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
